### ISSUE TITLE
Blocking event loop each time an event is sent

### ISSUE THREAD

**Issue by dgrelaud** [Countly/countly-sdk-nodejs#12]
Hello,

If I understand well the code, there is a readFileSync each time an event is sent? 😢
https://github.com/Countly/countly-sdk-nodejs/blob/7950cdae12c32d387f688ae0a1f45ba71a4068ea/lib/countly.js#L1435

It could create a performance bottleneck because it blocks NodeJS event loop.

Thank you.

**Comment by ar2rsawseen** [comment]
True
this can be improved on next release

**Comment by dgrelaud** [comment]
Nice, thank you 😉 

BTW, I was happy to find such a **light** SDK , without any dependencies 👍.

**Comment by ar2rsawseen** [comment]
This should be fixed here: https://github.com/Countly/countly-sdk-nodejs/commit/844498b975dc7db658cf3eb559dd0fea4eb0a5ab
Thank you for the suggestion :)
