### ISSUE TITLE
call to `store("cly_id", Countly.device_id);`

### ISSUE THREAD

**Issue by mikael-entefy** [Countly/countly-sdk-nodejs#3]
At this  [line](https://github.com/Countly/countly-sdk-nodejs/blob/master/lib/countly.js#L193) you do this:
```javascript
        store("cly_id", Countly.device_id);
```
It should probably be:
```javascript
        storeSet("cly_id", Countly.device_id);
```

**Comment by ar2rsawseen** [comment]
Whoops, copy paste error, fixed here:
https://github.com/Countly/countly-sdk-nodejs/commit/4478cb1815427192076040fe1d1c23c5252778d2

Thank you for reporting
