### ISSUE TITLE
Custom _os and _os_version metrics not taken into account

### ISSUE THREAD

**Issue by joelrobichaud** [Countly/countly-sdk-nodejs#4]
Custom `_os` and `_os_version` properties specified inside the init options are not taken into account when sending analytics. 

For example, the values specified in init
```
Countly.init({
    metrics: {
        _os: '<my custom os>',
        _os_version: '<my custom os version>'
    }
});
```
Gets replaced as follows when analytics are sent:
- `_os` gets replaced by node's `os.type()`
- `_os_version` gets replaced by node's `os.release()`

**Comment by ar2rsawseen** [comment]
Hello,
fixed here:
https://github.com/Countly/countly-sdk-nodejs/commit/0c8285f696bd646f45de1fe4b0579772b649fd91
