### ISSUE TITLE
[ERROR] add_bulk_request, incorrect timestamp format

### ISSUE THREAD

**Issue by farai-bws** [Countly/countly-sdk-nodejs#48]
Hi,

I'm trying to do this from the examples (http://countly.github.io/countly-sdk-nodejs/module-lib_countly-bulk.html):

`var server = new CountlyBulk({`
`  app_key: "{YOUR-API-KEY}",`
`  url: "https://api_host/",`
`  debug: true`
`});`
`server.add_bulk_request([{app_key:"somekey", devide_id:"someid", begin_session:1}, {app_key:"somekey", devide_id:"someid", events:"[{'key':'val','count':1}]"}]);`

But I get this error: **[ERROR] add_bulk_request, incorrect timestamp format**

**Comment by turtledreams** [comment]
Hello there, you can ignore that log that if you have not provided any timestamp values in your request. It is actually a warning about the timestamp value (expects milliseconds or seconds and gives a warning if it can not see that).
