### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by adammeyer** [Countly/countly-sdk-nodejs#9]
It would be great if this library could support proxies or at least a way to pass in a custom agent (https://nodejs.org/api/http.html#http_class_http_agent).  Currently users that require a proxy are not sending any analytics.

**Comment by ar2rsawseen** [comment]
Added ability to override http options for each request:
https://github.com/Countly/countly-sdk-nodejs/commit/4556575160555aaa1c0b809010609a72cb452b71

This way you can add agent, or override host with proxy and pass path as header for each separate request
